"""initial migration

Revision ID: d760d17516d9
Revises:
Create Date: 2025-10-06 20:08:01.014478

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d760d17516d9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("balance_cent", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("balance_cent >= 0", name="check_balance_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column(
            "operation_type",
            sa.Enum("DEPOSIT", "WITHDRAWAL", name="operationtype"),
            nullable=False,
        ),
        sa.Column("amount_cent", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operations_created_at"), "operations", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_operations_id"), "operations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operations_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_created_at"), table_name="operations")
    op.drop_table("operations")
    op.drop_table("wallets")
    op.execute("DROP TYPE IF EXISTS operationtype;")
    # ### end Alembic commands ###
